version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:us-east-1:231544052460:task-definition/art-gallery-manual:2
        LoadBalancerInfo:
          ContainerName: my_art_gallery_prod
          ContainerPort: 3000
        PlatformVersion: "LATEST"
